package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BOX.
 */
public class Box {

    private Long id;
    private String name;
    private Integer slots;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Box() {
    }

    public Box(Long id) {
        this.id = id;
    }

    public Box(Long id, String name, Integer slots, String description) {
        this.id = id;
        this.name = name;
        this.slots = slots;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getSlots() {
        return slots;
    }

    public void setSlots(Integer slots) {
        this.slots = slots;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "Box{" +
                "name='" + name + '\'' +
                ", description='" + description + '\'' +
                '}';
    }

    // KEEP METHODS END

}
